---
#On crée un dossier via le module file
    - name: Créer un répertoire s'il n'existe pas
      ansible.builtin.file:
        path: /tmp/curlcmd
        state: directory
        mode: '0755'

  #Récupération du fichier setup_16.x via le module curl et création d'un script avec le contenu de ce fichier
    - name: Téléchargement de curl 
      ansible.builtin.get_url:
        url: https://deb.nodesource.com/setup_16.x
        dest: /tmp/curlcmd/curlsetup.sh
  
  #Modification des permissions du script curlsetup.sh ajout du mode executable (+x)
    - name: Ajout des persmissions "+x"
      file: dest=/tmp/curlcmd/curlsetup.sh mode=a+x

  #Execution du script
    - name: execution du script 
      shell: /tmp/curlcmd/curlsetup.sh