---
  #Ajout d'un variable d'environement pour autoriser à prendre maximum 4 go de ram à npm
    - name: correction mémoire insuffisante npm i
      lineinfile:
        path: ~/.profile
        line: "export NODE_OPTIONS=--max-old-space-size={{ dedicated_ram }}"
        insertafter: EOF

  #Installation des dependances npm via le module npm
    - name: Installation des dépendances npm
      npm:
        path: /home/mastodon/
        state: present