---
  #On installe la première partie des dépendances utilisés par mastodon via le module apt 
    - name: Installation premiere partie des packages
      apt:
        name: "{{ item }}"
        state: present
        update_cache: yes
      loop:
          - curl
          - wget
          - gnupg
          - apt-transport-https
          - lsb-release
          - ca-certificates
