--- 

  #Creation d'une base de donnée nommée mastodon via le module postgresql_db
    - name: Creation de la base de donnée Mastodon
      become_user: "{{ db }}"
      postgresql_db:
        name: "{{ DB_USER }}" #mastodon
        state: present

  #Creation de l'utilisateur mastodon qui a le privilège de créer des bases de données via le module postgresql_user
    - name: Creation utilisateur mastodon et autorisation de creer des bases de données
      become_user: "{{ db }}"
      postgresql_user:
        name: "{{ DB_USER }}"
        password: "{{ DB_PASS }}"
        role_attr_flags: CREATEDB

  #Donner les privileges à l'utilisateur mastodon via le module postgresql_privs
    - name: Don de tous les privileges a l utilisateur mastdon
      postgresql_privs:
        type: database
        database: "{{ DB_USER }}"
        roles: "{{ DB_USER }}"
        grant_option: false
        privs: all
      become_user: "{{ db }}"

  #Donner privileges utilisateur mastodon pour créer les bases de données
    - name: autorisation de l'utilisateur a creer des bases de données
      become_user: "{{ db }}"
      community.postgresql.postgresql_user:
        name: "{{ DB_USER }}"
        role_attr_flags: CREATEDB