---
  #Clone du dépot de git rbenv via module git
    - name: Changement de user en mastodon et Clone de rbenv git
      become_user: mastodon
      git:
          repo: https://github.com/rbenv/rbenv.git
          dest: ~/.rbenv
          force: yes

  #"make" de la configuration de rbenv
    - name: make configure ##Trouver autre solution
      become_user: mastodon
      shell: cd ~/.rbenv && src/configure && make -C src

  #Ajout de  variables d'environnements au fichier .bashrc via le module lineinfile
    - name: Add rbenv to PATH
      become_user: mastodon
      lineinfile:
        path: ~/.bashrc
        line: "{{ item }}"
        insertafter: EOF
      loop:
         - export PATH="$HOME/.rbenv/bin:$PATH"
         - eval "$(rbenv init -)"

  #Ajout d'un nouveau PATH à la variable PATH et lancement du script rbenv
    - name: Script Ruby 
      become_user: mastodon
      shell: |
          export PATH=$HOME/.rbenv/bin:$PATH
          eval "$(rbenv init -)"

  #Clone du dépot de git ruby via module git
    - name: Changement de user en mastodon et Clone de ruby git
      become_user: mastodon
      git:
          repo: https://github.com/rbenv/ruby-build.git
          dest: ~/.rbenv/plugins/ruby-build
          force: yes

  #Installation de rbenv sous l'utilisateur mastodon
    - name: Rbenv Global
      shell: | 
          RUBY_CONFIGURE_OPTS=--with-jemalloc ~/.rbenv/bin/rbenv install $(cat live/.ruby-version)
          ~/.rbenv/bin/rbenv global $(cat live/.ruby-version)
      become_user: mastodon
      args: 
        chdir: /home/mastodon
        ## #$(rbenv install --list | grep -v - | tail -1)
        # Vrbenv=$(cat live/.ruby-version)
          # $Vrbenv >> ~/.bashrc
          # RUBY_CONFIGURE_OPTS=--with-jemalloc ~/.rbenv/bin/rbenv install $Vrbenv
          # ~/.rbenv/bin/rbenv global $Vrbenv



  #Installation du package pyscopg2 via le module pip
    - name: Install bottle python package
      ansible.builtin.pip:
        name: psycopg2